import React, { Component } from 'react';
import styled from 'styled-components';

import Slider from 'react-slick';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import '../styles/slider.css';


const Wrap = styled.div`
  display: flex;
  flex-flow: column;
  align-items: center;
  width: 100%;
  margin: 1em 0;
`;

const InnerWrap = styled.div`
  display: flex;
  flex-flow: column;
  align-items: center;
  width: 95%;
`;

const TopInfo = styled.div`
  display: flex;
  flex-flow: column;
  align-items: flex-start;
  width: 100%;

  & > h2 {
    font-size: 2em;
    margin: 0;
    padding: 0;
  }

  & > h3 {
    font-size: 1em;
    font-weight: 400;
    margin: 0;
    padding: 0;
  }
`;

const SkillsList = styled.ul`
  display: flex;
  flex-flow: column;
  padding: 0;
  margin: 0;
  justify-content: center;
  align-items: flex-start;
  width: 100%;
  list-style-type: none;
  color: white;
  margin-top: 5vh;
`;

const Skill = styled.li`
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 1em;
  padding: 0.25em 0.5em;
  margin: 0;
  background-color: #1a1a1d;
`;

const SliderW = styled.div`
  width: 100%;
`;

const ImageW = styled.div`
  width: 100%;
`;

const Image = styled.img`
  width: 100%;
  height: auto;
  // background-image: url('${require("../images/pogtracker-2.png")}');
  // background-repeat: no-repeat;
  // background-size: contain;
`;

const sliderSettings = {
  dots: true,
  slidesToShow: 1,
  slidesToScroll: 1,
  infinite: false,
  arrows: false
}

class ProjectCard extends Component {
  render() {
    return (
      <Wrap>
        <InnerWrap>
          <TopInfo>
            <h2>POGTRACKER</h2>
            <h3>Twitch highlights generated by chat activity</h3>
          </TopInfo>
          <SliderW>
            <Slider {...sliderSettings}>
              <div>
                <ImageW>
                  <Image src={require("../images/pogtracker-2.png")}/>
                </ImageW>
              </div>
              <div>
                <ImageW>
                  <Image src={require("../images/pogtracker-2.png")}/>
                </ImageW>
              </div>
              <div>
                <ImageW>
                  <Image src={require("../images/pogtracker-2.png")}/>
                </ImageW>
              </div>
            </Slider>
          </SliderW>
          <SkillsList>
            <Skill>MongoDB</Skill>
            <Skill>Node</Skill>
            <Skill>Express</Skill>
            <Skill>React Router 4</Skill>
            <Skill>Dokku</Skill>
          </SkillsList>
        </InnerWrap>
      </Wrap>
    );
  }
}

export default ProjectCard;